In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('source.csv')

In [3]:
data.head()

       Name                 Datetime  Amount  Price  Purity
0  ProductA  2022-01-01T01:00:00.000      10  22.09  Impure
1  ProductA  2022-01-01T02:00:00.000      15  24.22    Pure
2  ProductA  2022-01-01T03:00:00.000      10  25.96  Impure
3  ProductA  2022-01-01T04:00:00.000      20  21.16  Impure
4  ProductA  2022-01-01T05:00:00.000      10  20.05    Pure

In [4]:
data.dtypes

Name         object
Datetime     object
Amount        int64
Price       float64
Purity       object
dtype: object

In [5]:
data['Datetime']=pd.to_datetime(data['Datetime'],utc=True)

In [6]:
data.dtypes

Name                     object
Datetime    datetime64[ns, UTC]
Amount                    int64
Price                   float64
Purity                   object
dtype: object

In [7]:
data.head(2)

       Name                  Datetime  Amount  Price  Purity
0  ProductA 2022-01-01 01:00:00+00:00      10  22.09  Impure
1  ProductA 2022-01-01 02:00:00+00:00      15  24.22    Pure

In [8]:
data['Datetime']=data['Datetime'].dt.tz_convert('Etc/GMT-6')

In [9]:
data.head(2)

       Name                  Datetime  Amount  Price  Purity
0  ProductA 2022-01-01 07:00:00+06:00      10  22.09  Impure
1  ProductA 2022-01-01 08:00:00+06:00      15  24.22    Pure

In [10]:
data['total']=np.nan

In [11]:
for row in range(len(data)):
    if data.iloc[row,0]=='ProductA' and data.iloc[row,4]=="Pure":
        data.iloc[row,-1]=data.iloc[row,2]*data.iloc[row,3]
    elif data.iloc[row,0]=='ProductB' and data.iloc[row,4]=="Pure":
        for line in range(len(data)):
            if data.iloc[line,0]=='ProductA' and data.iloc[row,1]==data.iloc[line,1]:
                data.iloc[row,-1]=(data.iloc[row,3]-data.iloc[line,3])*data.iloc[row,2]
    else: data.iloc[row,-1]=data.iloc[row,3]*0.75

In [12]:
data.to_csv('result.csv',index=False)